name: Build and Release WCA
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build and Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 1. Ajuste Versao
          sed -i 's/AppVersion.*/AppVersion             = "v1.0.5"/' src/config/settings.go
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add src/config/settings.go
          git commit -m "chore: version 1.0.5"
          git tag v1.0.5
          git push origin main
          git push origin v1.0.5
          
          # 2. Build
          cd src
          go build -trimpath -ldflags="-s -w" -o whatsapp-wca-aarch64.bin .
          mv whatsapp-wca-aarch64.bin ../
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.5
          name: "🚀 Release v1.0.5"
          body: |
            ### 🤖 WCA - WhatsApp WCA (aarch64) - Versão v1.0.5
            
            ---
            ### 📂 Instalação
            1. Coloque o binário `whatsapp-wca-aarch64.bin` em: `/data/data/net.dinglisch.android.taskerm/files/WCA/`
            
            ---
            ### ⚙️ Executar no Tasker (Java Code)
            ```java
            Runtime rt = Runtime.getRuntime(); String[] cmd = new String[]{"/system/bin/sh","-c","cd /data/data/net.dinglisch.android.taskerm/files/WCA && nohup /system/bin/linker64 /data/data/net.dinglisch.android.taskerm/files/WCA/whatsapp-wca-aarch64.bin rest --port 3000 </dev/null >/dev/null 2>&1 &"}; rt.exec(cmd);
            ```
            
            ### 🛑 Parar API (Run Shell)
            ```bash
            pid=$(ps -e -o PID,ARGS | grep "whatsapp-wca-aarch64" | grep -v grep | awk '{print $1}') && [ -n "$pid" ] && kill -9 $pid && echo "Process terminated" || echo "Process not found"
            ```
            
            ### 🔍 Verificar API (Run Shell)
            ```bash
            sleep 0.2
            pgrep -f whatsapp-wca-aarch64 >/dev/null && echo "wca running" || echo "wca not running"
            ```
          files: whatsapp-wca-aarch64.bin
